### ISSUE TITLE
Project currently targets old .Net Framework version. Update it?

### ISSUE THREAD

**Issue by neotamias** [raburton/god2iso#3]
![image](https://user-images.githubusercontent.com/45723396/104092266-d5a2a700-5250-11eb-90e6-b60b722a4604.png)

**Comment by raburton** [comment]
Hi, Only just spotted this issue, I didn't get an email notification about it.

Is there any particular reason to increase the target? It builds perfectly well with latest version of Visual Studio (2019) and runs fine.
